Add CI workflow for Ansible backup playbook

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,4 +1,4 @@
-name: CI Pipeline
+name: CI for Ansible Backup Playbook
 
 on:
   push:
@@ -9,22 +9,37 @@ on:
       - main
 
 jobs:
-  run-playbook:
+  test-playbook:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout Code
-        uses: actions/checkout@v3
+    - name: Checkout code
+      uses: actions/checkout@v3
 
-      - name: Set up Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: '3.8'
+    - name: Set up Python
+      uses: actions/setup-python@v4
+      with:
+        python-version: '3.9'
 
-      - name: Install Ansible
-        run: |
-          python -m pip install --upgrade pip
-          pip install ansible
+    - name: Install Ansible
+      run: |
+        python -m pip install --upgrade pip
+        pip install ansible
 
-      - name: Run Ansible Playbook
-        run: ansible-playbook install.yaml -i hosts.yaml
+    - name: Run Ansible Playbook
+      run: |
+        ansible-playbook -i hosts.yaml  install.yaml
+
+    - name: Check Backup File
+      run: |
+        if [ ! -f "backup/backup_*.sql.gz" ]; then
+          echo "Backup file not found!"
+          exit 1
+        else
+          echo "Backup file found."
+        fi
+
+    - name: List Backup Files
+      run: |
+        ls -la backup/
+
